In [1]:
import numpy as np

In [2]:
np.arange(19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [3]:
a = [1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
a = np.array(a)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [5]:
np.arange(-3,3,0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [6]:
np.arange(-3,3,0.5, dtype=float)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [7]:
l = [i**2 for i in range(100)]

In [8]:
l

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [9]:
l = range(100000)
%timeit [i**2 for i in l]

34.1 ms ± 4.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
a = np.arange(10000000)
%timeit a**2

44.6 ms ± 11.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
a = [1,2,3,4,5]
a = np.array(a)

In [12]:
a.ndim

1

In [13]:
a % 2

array([1, 0, 1, 0, 1])

In [14]:
a.shape

(5,)

In [15]:
b = np.array([[1,2,3],[4,5,6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
b.shape[0], b.shape[1]

(2, 3)

In [20]:
import pandas as pd

In [21]:
pd.DataFrame(b)

0  1  2
0  1  2  3
1  4  5  6

In [22]:
x = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

In [23]:
x = np.array(x)

In [24]:
x.ndim

3

In [ ]:
d = list(map(int, input().split()))

In [ ]:
n, m = list(map(int, input("Enter the number of rows and column: ").split(",")))
A = np.array([input(f"Row{i+1}: ").split(",")[:m] for i in range(n)], int)
print(A)
type(A)

In [ ]:
b = np.linspace(1,4,10)

In [ ]:
c = np.ones((4,5))
c

In [ ]:
d = np.zeros((4,4))

In [ ]:
e = np.eye(3,3)

In [ ]:
np.diag(e)

In [ ]:
n = int(input(f'Enter "nth" number: '))
g = np.random.rand(n)
print(g)

In [ ]:
h = np.random.rand(3)
h
h.dtype

In [ ]:
c = np.array([1+2j,3+4j])
print(c)
print(c.dtype)

In [ ]:
b = np.array([True,True,False,False])
print(b)
print(b.dtype)

In [ ]:
a = np.diag([1,2,3,4])
print(a)
a[2:4] = 5
print(a)

In [ ]:
a

In [ ]:
a[0] = 1000

In [ ]:
c = a[::2].copy()

In [ ]:
c

In [ ]:
np.shares_memory(a,c)

In [ ]:
b = np.random.randint(20,30,10)